// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_HoA5irFVEAKqlXPdR4eRnoPEP1wM4b0',
    appId: '1:1081615758678:web:59c01e11b36354ff8f92f7',
    messagingSenderId: '1081615758678',
    projectId: 'shop-app-b01ec',
    authDomain: 'shop-app-b01ec.firebaseapp.com',
    databaseURL: 'https://shop-app-b01ec-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-b01ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKsJmYBePTNu59l4f9nWUl6TuuKVxYOM4',
    appId: '1:1081615758678:android:5ddf7d793e188c538f92f7',
    messagingSenderId: '1081615758678',
    projectId: 'shop-app-b01ec',
    databaseURL: 'https://shop-app-b01ec-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-b01ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD709UH942-9GguKDWSdwEIIVubkYdxNmc',
    appId: '1:1081615758678:ios:86994f41f5c38a878f92f7',
    messagingSenderId: '1081615758678',
    projectId: 'shop-app-b01ec',
    databaseURL: 'https://shop-app-b01ec-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-b01ec.firebasestorage.app',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD709UH942-9GguKDWSdwEIIVubkYdxNmc',
    appId: '1:1081615758678:ios:86994f41f5c38a878f92f7',
    messagingSenderId: '1081615758678',
    projectId: 'shop-app-b01ec',
    databaseURL: 'https://shop-app-b01ec-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-b01ec.firebasestorage.app',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_HoA5irFVEAKqlXPdR4eRnoPEP1wM4b0',
    appId: '1:1081615758678:web:a5fa894afd9063d38f92f7',
    messagingSenderId: '1081615758678',
    projectId: 'shop-app-b01ec',
    authDomain: 'shop-app-b01ec.firebaseapp.com',
    databaseURL: 'https://shop-app-b01ec-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-b01ec.firebasestorage.app',
  );

}